//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contensive.Processor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Contensive.Processor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;nav class=&quot;navbar navbar-expand-md navbar-dark bg-dark&quot;&gt;
        ///&lt;a class=&quot;navbar-brand&quot; href=&quot;/&quot;&gt;{navBrand}&lt;/a&gt;
        ///&lt;div class=&quot;navbar-text mr-auto&quot;&gt;{leftSideMessage}&lt;/div&gt;
        ///&lt;div class=&quot;navbar-text ml-auto&quot;&gt;{rightSideMessage}&lt;/div&gt;
        ///{rightSideNavHtml}
        ///&lt;/nav&gt;.
        /// </summary>
        public static string adminNavBarHtml {
            get {
                return ResourceManager.GetString("adminNavBarHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;container-fluid&quot;&gt;
        ///	&lt;h4 class=&quot;form-signin-heading&quot;&gt;Forget Your Password&lt;/h4&gt;
        ///	&lt;!--&lt;p&gt;If you are a member of the system and cannot remember your password, enter your email address below and we will email your matching username(s) and password(s).&lt;/p&gt;--&gt;
        ///	&lt;div class=&quot;pt-2&quot;&gt;
        ///		&lt;label for=&quot;inputEmail&quot; class=&quot;sr-only pt-2&quot;&gt;Email address&lt;/label&gt;
        ///		&lt;input type=&quot;email&quot; name=&quot;username&quot; id=&quot;inputEmail&quot; class=&quot;form-control pt-2&quot; placeholder=&quot;Username&quot; required autofocus&gt;
        ///	&lt;/div&gt;
        ///	&lt;div class=&quot;pt-2&quot;&gt;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string defaultForgetPassword_html {
            get {
                return ResourceManager.GetString("defaultForgetPassword_html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;container-fluid&quot;&gt;
        ///    &lt;h4 class=&quot;form-signin-heading&quot;&gt;Login&lt;/h4&gt;
        ///	&lt;div class=&quot;pt-2&quot;&gt;
        ///		&lt;label for=&quot;inputUsername&quot; class=&quot;sr-only&quot;&gt;Email address&lt;/label&gt;
        ///		&lt;input type=&quot;text&quot; name=&quot;username&quot; id=&quot;inputUsername&quot; class=&quot;form-control&quot; placeholder=&quot;Username&quot; required autofocus&gt;
        ///	&lt;/div&gt;
        ///	&lt;div class=&quot;pt-2&quot;&gt;
        ///	    &lt;label for=&quot;inputPassword&quot; class=&quot;sr-only&quot;&gt;Password&lt;/label&gt;
        ///		&lt;input type=&quot;password&quot; name=&quot;password&quot; id=&quot;inputPassword&quot; class=&quot;form-control&quot; placeholder=&quot;Password&quot; required&gt;
        ///	&lt;/div&gt;
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        public static string defaultLogin_autoLogin_html {
            get {
                return ResourceManager.GetString("defaultLogin_autoLogin_html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;container-fluid&quot;&gt;
        ///    &lt;h4 class=&quot;form-signin-heading&quot;&gt;Login&lt;/h4&gt;
        ///    &lt;label for=&quot;inputEmail&quot; class=&quot;sr-only&quot;&gt;Email address&lt;/label&gt;
        ///    &lt;input type=&quot;email&quot; name=&quot;email&quot; id=&quot;inputEmail&quot; class=&quot;form-control&quot; placeholder=&quot;Username or Email&quot; required autofocus&gt;
        ///    &lt;label for=&quot;inputPassword&quot; class=&quot;sr-only&quot;&gt;Password&lt;/label&gt;
        ///    &lt;input type=&quot;password&quot; name=&quot;password&quot; id=&quot;inputPassword&quot; class=&quot;form-control&quot; placeholder=&quot;Password&quot; required&gt;
        ///    &lt;div class=&quot;checkbox pt-2&quot;&gt;
        ///        &lt;label&gt;
        ///        [rest of string was truncated]&quot;;.
        /// </summary>
        public static string defaultLogin_email_autoLogin_html {
            get {
                return ResourceManager.GetString("defaultLogin_email_autoLogin_html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;container-fluid&quot;&gt;
        ///    &lt;h4 class=&quot;form-signin-heading&quot;&gt;Login&lt;/h4&gt;
        ///	&lt;div class=&quot;pt-2&quot;&gt;
        ///		&lt;label for=&quot;inputEmail&quot; class=&quot;sr-only&quot;&gt;Email address&lt;/label&gt;
        ///		&lt;input type=&quot;text&quot; name=&quot;username&quot; id=&quot;inputEmail&quot; class=&quot;form-control&quot; placeholder=&quot;Username or Email&quot; required autofocus&gt;
        ///    &lt;/div&gt;
        ///	&lt;div class=&quot;pt-2&quot;&gt;
        ///		&lt;label for=&quot;inputPassword&quot; class=&quot;sr-only&quot;&gt;Password&lt;/label&gt;
        ///		&lt;input type=&quot;password&quot; name=&quot;password&quot; id=&quot;inputPassword&quot; class=&quot;form-control&quot; placeholder=&quot;Password&quot; required&gt;
        ///    &lt;/div [rest of string was truncated]&quot;;.
        /// </summary>
        public static string defaultLogin_email_html {
            get {
                return ResourceManager.GetString("defaultLogin_email_html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;container-fluid&quot;&gt;
        ///    &lt;h4 class=&quot;form-signin-heading&quot;&gt;Login&lt;/h4&gt;
        ///	&lt;div class=&quot;pt-2&quot;&gt;
        ///		&lt;label for=&quot;inputUsername&quot; class=&quot;sr-only&quot;&gt;Email address&lt;/label&gt;
        ///		&lt;input type=&quot;text&quot; name=&quot;username&quot; id=&quot;inputUsername&quot; class=&quot;form-control&quot; placeholder=&quot;Username&quot; required autofocus&gt;
        ///	&lt;/div&gt;
        ///	&lt;div class=&quot;pt-2&quot;&gt;
        ///	    &lt;label for=&quot;inputPassword&quot; class=&quot;sr-only&quot;&gt;Password&lt;/label&gt;
        ///		&lt;input type=&quot;password&quot; name=&quot;password&quot; id=&quot;inputPassword&quot; class=&quot;form-control&quot; placeholder=&quot;Password&quot; required&gt;
        ///	&lt;/div&gt;
        ///	&lt;d [rest of string was truncated]&quot;;.
        /// </summary>
        public static string defaultLogin_html {
            get {
                return ResourceManager.GetString("defaultLogin_html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;nav class=&quot;navbar navbar-expand-md navbar-dark bg-dark&quot;&gt;
        ///	&lt;a class=&quot;navbar-brand&quot; href=&quot;#&quot;&gt;Brand&lt;/a&gt;
        ///	{% {&quot;addon&quot;:{&quot;addon&quot;:&quot;Bootstrap Nav 40&quot;,&quot;instanceId&quot;:&quot;Home Top Nav&quot;}} %}
        ///&lt;/nav&gt;
        ///&lt;div class=&quot;container&quot;&gt;
        ///    &lt;div class=&quot;row&quot;&gt;
        ///        &lt;div class=&quot;col-lg-12 mt-2&quot;&gt;
        ///            {% &quot;Content Box&quot; %}
        ///        &lt;/div&gt;
        ///    &lt;/div&gt;
        ///&lt;/div&gt;.
        /// </summary>
        public static string DefaultTemplateHtml {
            get {
                return ResourceManager.GetString("DefaultTemplateHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;tr&gt;
        ///    &lt;td class=&quot;ccAdminEditCaption&quot;&gt;{{rowCaption}}&lt;/td&gt;
        ///    &lt;td class=&quot;ccAdminEditField&quot;&gt;
        ///        &lt;table border=&quot;0&quot; cellpadding=&quot;0&quot; cellspacing=&quot;0&quot; width=&quot;100%&quot;&gt;
        ///            &lt;tbody&gt;
        ///                &lt;tr&gt;
        ///                    &lt;td width=&quot;40%&quot;&gt;{{{checkboxInput}}}{{groupCaption}}&lt;/td&gt;
        ///                    &lt;td width=&quot;30%&quot;&gt;Expires{{{expiresInput}}}&lt;/td&gt;
        ///                    &lt;td width=&quot;30%&quot;&gt;{{{relatedButtonList}}}{{{idHidden}}}&lt;/td&gt;
        ///                &lt;/tr&gt;
        ///            &lt;/tbody&gt;
        ///        &lt;/table&gt;
        ///    &lt;/td&gt;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GroupRuleEditorRow {
            get {
                return ResourceManager.GetString("GroupRuleEditorRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;p-2 ccEditRow&quot;&gt;
        ///    &lt;!-- list caption --&gt;
        ///    &lt;label for=&quot;name432&quot;&gt;{{listCaption}}&lt;/label&gt;
        ///    &lt;!-- list --&gt;
        ///    &lt;div class=&quot;ml-5&quot;&gt;
        ///        {{#rowList}}
        ///        &lt;!-- row repeat --&gt;
        ///        &lt;div class=&quot;row pb-1 border-bottom border-light&quot;&gt;
        ///            &lt;!-- checkbox and group name --&gt;
        ///            &lt;div class=&quot;col-sm-4&quot;&gt;&lt;label class=&quot;checkbox-inline&quot;&gt;{{{checkboxInput}}}&amp;nbsp;{{{groupCaption}}}&lt;/label&gt;&lt;/div&gt;
        ///            &lt;!-- expiration date --&gt;
        ///            &lt;div class=&quot;col-sm-4&quot;&gt;{{{expiresI [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GroupRuleEditorRow2 {
            get {
                return ResourceManager.GetString("GroupRuleEditorRow2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;form class=&quot;form-inline&quot; method=&quot;post&quot; action=&quot;?method=login&quot;&gt;
        ///&lt;button class=&quot;btn btn-warning btn-sm ml-2&quot; type=&quot;submit&quot;&gt;Login&lt;/button&gt;
        ///&lt;/form&gt;.
        /// </summary>
        public static string LoginButtonFormHtml {
            get {
                return ResourceManager.GetString("LoginButtonFormHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;form class=&quot;form-inline&quot; method=&quot;post&quot; action=&quot;?method=logout&quot;&gt;
        ///{{personName}}&amp;nbsp;&lt;button class=&quot;btn btn-warning btn-sm ml-2&quot; type=&quot;submit&quot;&gt;Logout&lt;/button&gt;
        ///&lt;/form&gt;.
        /// </summary>
        public static string LogoutButtonFormHtml {
            get {
                return ResourceManager.GetString("LogoutButtonFormHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TRIGGER ccManyManyRuleDelete_{ruleTable}_{ruleField}
        ///ON {joinTable}
        ///AFTER UPDATE,DELETE
        ///AS
        ///delete from {ruleTable} 
        ///from {ruleTable} r 
        ///left join {joinTable} a on a.{joinField}=r.{ruleField} where a.id is null
        ///
        ///--sample
        ///--CREATE TRIGGER ccManyManyRuleDelete_ccAddonContentFieldTypeRules_addonId
        ///--ON ccAggregateFunctions
        ///--AFTER  UPDATE,DELETE
        ///--AS
        ///--delete  from ccAddonContentFieldTypeRules 
        ///--from ccAddonContentFieldTypeRules r 
        ///--left join ccAggregateFunctions a on a.id=r.addonid wher [rest of string was truncated]&quot;;.
        /// </summary>
        public static string sqlTriggerManyManyRule {
            get {
                return ResourceManager.GetString("sqlTriggerManyManyRule", resourceCulture);
            }
        }
    }
}
