//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contensive.Processor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Contensive.Processor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;container-fluid&quot;&gt;
        ///	&lt;h4 class=&quot;form-signin-heading&quot;&gt;Forget Your Password&lt;/h4&gt;
        ///	&lt;!--&lt;p&gt;If you are a member of the system and cannot remember your password, enter your email address below and we will email your matching username(s) and password(s).&lt;/p&gt;--&gt;
        ///	&lt;div class=&quot;pt-2&quot;&gt;
        ///		&lt;label for=&quot;inputEmail&quot; class=&quot;sr-only pt-2&quot;&gt;Email address&lt;/label&gt;
        ///		&lt;input type=&quot;email&quot; name=&quot;username&quot; id=&quot;inputEmail&quot; class=&quot;form-control pt-2&quot; placeholder=&quot;Username&quot; required autofocus&gt;
        ///	&lt;/div&gt;
        ///	&lt;div class=&quot;pt-2&quot;&gt;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string defaultForgetPassword_html {
            get {
                return ResourceManager.GetString("defaultForgetPassword_html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;container-fluid&quot;&gt;
        ///    &lt;h4 class=&quot;form-signin-heading&quot;&gt;Login&lt;/h4&gt;
        ///	&lt;div class=&quot;pt-2&quot;&gt;
        ///		&lt;label for=&quot;inputUsername&quot; class=&quot;sr-only&quot;&gt;Email address&lt;/label&gt;
        ///		&lt;input type=&quot;text&quot; name=&quot;username&quot; id=&quot;inputUsername&quot; class=&quot;form-control&quot; placeholder=&quot;Username&quot; required autofocus&gt;
        ///	&lt;/div&gt;
        ///	&lt;div class=&quot;pt-2&quot;&gt;
        ///	    &lt;label for=&quot;inputPassword&quot; class=&quot;sr-only&quot;&gt;Password&lt;/label&gt;
        ///		&lt;input type=&quot;password&quot; name=&quot;password&quot; id=&quot;inputPassword&quot; class=&quot;form-control&quot; placeholder=&quot;Password&quot; required&gt;
        ///	&lt;/div&gt;
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        public static string defaultLogin_autoLogin_html {
            get {
                return ResourceManager.GetString("defaultLogin_autoLogin_html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;container-fluid&quot;&gt;
        ///    &lt;h4 class=&quot;form-signin-heading&quot;&gt;Login&lt;/h4&gt;
        ///    &lt;label for=&quot;inputEmail&quot; class=&quot;sr-only&quot;&gt;Email address&lt;/label&gt;
        ///    &lt;input type=&quot;email&quot; name=&quot;email&quot; id=&quot;inputEmail&quot; class=&quot;form-control&quot; placeholder=&quot;Username or Email&quot; required autofocus&gt;
        ///    &lt;label for=&quot;inputPassword&quot; class=&quot;sr-only&quot;&gt;Password&lt;/label&gt;
        ///    &lt;input type=&quot;password&quot; name=&quot;password&quot; id=&quot;inputPassword&quot; class=&quot;form-control&quot; placeholder=&quot;Password&quot; required&gt;
        ///    &lt;div class=&quot;checkbox pt-2&quot;&gt;
        ///        &lt;label&gt;
        ///        [rest of string was truncated]&quot;;.
        /// </summary>
        public static string defaultLogin_email_autoLogin_html {
            get {
                return ResourceManager.GetString("defaultLogin_email_autoLogin_html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;container-fluid&quot;&gt;
        ///    &lt;h4 class=&quot;form-signin-heading&quot;&gt;Login&lt;/h4&gt;
        ///	&lt;div class=&quot;pt-2&quot;&gt;
        ///		&lt;label for=&quot;inputEmail&quot; class=&quot;sr-only&quot;&gt;Email address&lt;/label&gt;
        ///		&lt;input type=&quot;text&quot; name=&quot;username&quot; id=&quot;inputEmail&quot; class=&quot;form-control&quot; placeholder=&quot;Username or Email&quot; required autofocus&gt;
        ///    &lt;/div&gt;
        ///	&lt;div class=&quot;pt-2&quot;&gt;
        ///		&lt;label for=&quot;inputPassword&quot; class=&quot;sr-only&quot;&gt;Password&lt;/label&gt;
        ///		&lt;input type=&quot;password&quot; name=&quot;password&quot; id=&quot;inputPassword&quot; class=&quot;form-control&quot; placeholder=&quot;Password&quot; required&gt;
        ///    &lt;/div [rest of string was truncated]&quot;;.
        /// </summary>
        public static string defaultLogin_email_html {
            get {
                return ResourceManager.GetString("defaultLogin_email_html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;container-fluid&quot;&gt;
        ///    &lt;h4 class=&quot;form-signin-heading&quot;&gt;Login&lt;/h4&gt;
        ///	&lt;div class=&quot;pt-2&quot;&gt;
        ///		&lt;label for=&quot;inputUsername&quot; class=&quot;sr-only&quot;&gt;Email address&lt;/label&gt;
        ///		&lt;input type=&quot;text&quot; name=&quot;username&quot; id=&quot;inputUsername&quot; class=&quot;form-control&quot; placeholder=&quot;Username&quot; required autofocus&gt;
        ///	&lt;/div&gt;
        ///	&lt;div class=&quot;pt-2&quot;&gt;
        ///	    &lt;label for=&quot;inputPassword&quot; class=&quot;sr-only&quot;&gt;Password&lt;/label&gt;
        ///		&lt;input type=&quot;password&quot; name=&quot;password&quot; id=&quot;inputPassword&quot; class=&quot;form-control&quot; placeholder=&quot;Password&quot; required&gt;
        ///	&lt;/div&gt;
        ///	&lt;d [rest of string was truncated]&quot;;.
        /// </summary>
        public static string defaultLogin_html {
            get {
                return ResourceManager.GetString("defaultLogin_html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;nav class=&quot;navbar navbar-default&quot; role=&quot;navigation&quot;&gt;
        ///    &lt;div class=&quot;navbar-collapse collapse&quot;&gt;
        ///        {% {&quot;addon&quot;:{&quot;addon&quot;:&quot;Menu Pages&quot;,&quot;instanceId&quot;:&quot;Home Top Nav&quot;}} %}
        ///    &lt;/div&gt;
        ///&lt;/nav&gt;
        ///&lt;div class=&quot;container&quot;&gt;
        ///    &lt;div class=&quot;row&quot;&gt;
        ///        &lt;div class=&quot;col-lg-12&quot;&gt;
        ///            {% &quot;Content Box&quot; %}
        ///        &lt;/div&gt;
        ///    &lt;/div&gt;
        ///&lt;/div&gt;.
        /// </summary>
        public static string DefaultTemplateHtml {
            get {
                return ResourceManager.GetString("DefaultTemplateHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;tr&gt;
        ///    &lt;td class=&quot;ccAdminEditCaption&quot;&gt;{{rowCaption}}&lt;/td&gt;
        ///    &lt;td class=&quot;ccAdminEditField&quot;&gt;
        ///        &lt;table border=&quot;0&quot; cellpadding=&quot;0&quot; cellspacing=&quot;0&quot; width=&quot;100%&quot;&gt;
        ///            &lt;tbody&gt;
        ///                &lt;tr&gt;
        ///                    &lt;td width=&quot;40%&quot;&gt;{{{checkboxInput}}}{{groupCaption}}&lt;/td&gt;
        ///                    &lt;td width=&quot;30%&quot;&gt;Expires{{{expiresInput}}}&lt;/td&gt;
        ///                    &lt;td width=&quot;30%&quot;&gt;{{{relatedButtonList}}}{{{idHidden}}}&lt;/td&gt;
        ///                &lt;/tr&gt;
        ///            &lt;/tbody&gt;
        ///        &lt;/table&gt;
        ///    &lt;/td&gt;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GroupRuleEditorRow {
            get {
                return ResourceManager.GetString("GroupRuleEditorRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;tr&gt;
        ///    &lt;td class=&quot;ccAdminEditCaption&quot;&gt;{{rowCaption}}&lt;/td&gt;
        ///    &lt;td class=&quot;ccAdminEditField&quot;&gt;
        ///        &lt;table border=&quot;0&quot; cellpadding=&quot;0&quot; cellspacing=&quot;0&quot; width=&quot;100%&quot;&gt;
        ///            &lt;tbody&gt;
        ///                &lt;tr&gt;
        ///                    &lt;td width=&quot;40%&quot;&gt;{{{checkboxInput}}}{{groupCaption}}&lt;/td&gt;
        ///                    &lt;td width=&quot;30%&quot;&gt;Expires{{{expiresInput}}}&lt;/td&gt;
        ///                    &lt;td width=&quot;30%&quot;&gt;{{{relatedButtonList}}}{{{idHidden}}}&lt;/td&gt;
        ///                &lt;/tr&gt;
        ///            &lt;/tbody&gt;
        ///        &lt;/table&gt;
        ///    &lt;/td&gt;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GroupRuleEditorRow2 {
            get {
                return ResourceManager.GetString("GroupRuleEditorRow2", resourceCulture);
            }
        }
    }
}
